<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RouteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $routes = [
            [
                'name' => 'From Kathamandu to Chitwan',
                'origin' => 'Kathamandu',
                'destination' => 'Chitwan',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '1',
            ],
            [
                'name' => 'From Kathamandu to Chitwan',
                'origin' => 'Kathamandu',
                'destination' => 'Chitwan',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '3',
            ],
            [
                'name' => 'From Kathamandu to Chitwan',
                'origin' => 'Kathamandu',
                'destination' => 'Chitwan',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '4',
            ],
            [
                'name' => 'From Kathamandu to Chitwan',
                'origin' => 'Kathamandu',
                'destination' => 'Chitwan',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '5',
            ],
            [
                'name' => 'From Pokhara to Kathamandu',
                'origin' => 'Pokhara',
                'destination' => 'Kathamandu',
                'via' => 'Bazaar, Damauli, Dumre, Muglin, Malekhu, Galchi, Naubise, Thankot',
                'distance' => '200',
                'company_id' => '1',
            ],
            [
                'name' => 'From Pokhara to Kathamandu',
                'origin' => 'Pokhara',
                'destination' => 'Kathamandu',
                'via' => 'Bazaar, Damauli, Dumre, Muglin, Malekhu, Galchi, Naubise, Thankot',
                'distance' => '200',
                'company_id' => '3',
            ],
            [
                'name' => 'From Pokhara to Kathamandu',
                'origin' => 'Pokhara',
                'destination' => 'Kathamandu',
                'via' => 'Bazaar, Damauli, Dumre, Muglin, Malekhu, Galchi, Naubise, Thankot',
                'distance' => '200',
                'company_id' => '4',
            ],
            [
                'name' => 'From Pokhara to Kathamandu',
                'origin' => 'Pokhara',
                'destination' => 'Kathamandu',
                'via' => 'Bazaar, Damauli, Dumre, Muglin, Malekhu, Galchi, Naubise, Thankot',
                'distance' => '200',
                'company_id' => '5',
            ],
            [
                'name' => 'From Pokhara to Chitwan',
                'origin' => 'Pokhara',
                'destination' => 'Chitwan',
                'via' => 'Bazaar, Damauli, Dumre, Muglin, Narayangarh',
                'distance' => '140',
                'company_id' => '1',
            ],
            [
                'name' => 'From Pokhara to Chitwan',
                'origin' => 'Pokhara',
                'destination' => 'Chitwan',
                'via' => 'Bazaar, Damauli, Dumre, Muglin, Narayangarh',
                'distance' => '140',
                'company_id' => '3',
            ],
            [
                'name' => 'From Pokhara to Chitwan',
                'origin' => 'Pokhara',
                'destination' => 'Chitwan',
                'via' => 'Bazaar, Damauli, Dumre, Muglin, Narayangarh',
                'distance' => '140',
                'company_id' => '4',
            ],
            [
                'name' => 'From Pokhara to Chitwan',
                'origin' => 'Pokhara',
                'destination' => 'Chitwan',
                'via' => 'Bazaar, Damauli, Dumre, Muglin, Narayangarh',
                'distance' => '140',
                'company_id' => '5',
            ],
            [
                'name' => 'From Baglung to Hetaunda',
                'origin' => 'Baglung',
                'destination' => 'Chitwan',
                'via' => 'Kusma, Pokhara, Bazaar, Damauli, Dumre, Muglin, Narayangarh, Manahari',
                'distance' => '175',
                'company_id' => '1',
            ],
            [
                'name' => 'From Chitwan to Pokhara',
                'origin' => 'Chitwan',
                'destination' => 'Pokhara',
                'via' => 'Narayangarh, Muglin, Dumre, Damauli, Bazaar',
                'distance' => '140',
                'company_id' => '1',
            ],
            [
                'name' => 'From Chitwan to Pokhara',
                'origin' => 'Chitwan',
                'destination' => 'Pokhara',
                'via' => 'Narayangarh, Muglin, Dumre, Damauli, Bazaar',
                'distance' => '140',
                'company_id' => '3',
            ],
            [
                'name' => 'From Chitwan to Pokhara',
                'origin' => 'Chitwan',
                'destination' => 'Pokhara',
                'via' => 'Narayangarh, Muglin, Dumre, Damauli, Bazaar',
                'distance' => '140',
                'company_id' => '4',
            ],
            [
                'name' => 'From Chitwan to Pokhara',
                'origin' => 'Chitwan',
                'destination' => 'Pokhara',
                'via' => 'Narayangarh, Muglin, Dumre, Damauli, Bazaar',
                'distance' => '140',
                'company_id' => '5',
            ],
            [
                'name' => 'From Chitwan to Kathamandu',
                'origin' => 'Chitwan',
                'destination' => 'Kathamandu',
                'via' => 'Narayangarh, Muglin, Malekhu, Galchi, Naubise, Thankot',
                'distance' => '145',
                'company_id' => '1',
            ],
            [
                'name' => 'From Chitwan to Kathamandu',
                'origin' => 'Chitwan',
                'destination' => 'Kathamandu',
                'via' => 'Narayangarh, Muglin, Malekhu, Galchi, Naubise, Thankot',
                'distance' => '145',
                'company_id' => '3',
            ],
            [
                'name' => 'From Chitwan to Kathamandu',
                'origin' => 'Chitwan',
                'destination' => 'Kathamandu',
                'via' => 'Narayangarh, Muglin, Malekhu, Galchi, Naubise, Thankot',
                'distance' => '145',
                'company_id' => '4',
            ],
            [
                'name' => 'From Chitwan to Kathamandu',
                'origin' => 'Chitwan',
                'destination' => 'Kathamandu',
                'via' => 'Narayangarh, Muglin, Malekhu, Galchi, Naubise, Thankot',
                'distance' => '145',
                'company_id' => '5',
            ],
            [
                'name' => 'From Kathamandu to Pokhara',
                'origin' => 'Kathamandu',
                'destination' => 'Pokhara',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Dumre, Damauli, Bazaar',
                'distance' => '200',
                'company_id' => '1',
            ],
            [
                'name' => 'From Kathamandu to Pokhara',
                'origin' => 'Kathamandu',
                'destination' => 'Pokhara',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Dumre, Damauli, Bazaar',
                'distance' => '200',
                'company_id' => '3',
            ],
            [
                'name' => 'From Kathamandu to Pokhara',
                'origin' => 'Kathamandu',
                'destination' => 'Pokhara',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Dumre, Damauli, Bazaar',
                'distance' => '200',
                'company_id' => '4',
            ],
            [
                'name' => 'From Kathamandu to Pokhara',
                'origin' => 'Kathamandu',
                'destination' => 'Pokhara',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Dumre, Damauli, Bazaar',
                'distance' => '200',
                'company_id' => '5',
            ],
            [
                'name' => 'From Chitwan to Butwal',
                'origin' => 'Chitwan',
                'destination' => 'Butwal',
                'via' => 'Narayangarh, Gaindakot, Bhedabari, 16no, Rajahar, Daldale, Kawasoti, Chormara, Bardaghat, Butwal',
                'distance' => '120',
                'company_id' => '2',
            ],
            [
                'name' => 'From Chitwan to Butwal',
                'origin' => 'Chitwan',
                'destination' => 'Butwal',
                'via' => 'Narayangarh, Gaindakot, Bhedabari, 16no, Rajahar, Daldale, Kawasoti, Chormara, Bardaghat, Butwal',
                'distance' => '120',
                'company_id' => '5',
            ],
            [
                'name' => 'From Chitwan to Butwal',
                'origin' => 'Chitwan',
                'destination' => 'Butwal',
                'via' => 'Narayangarh, Gaindakot, Bhedabari, 16no, Rajahar, Daldale, Kawasoti, Chormara, Bardaghat, Butwal',
                'distance' => '120',
                'company_id' => '6',
            ],
            [
                'name' => 'From Butwal to Chitwan',
                'origin' => 'Butwal',
                'destination' => 'Chitwan',
                'via' => 'Butwal, Bardaghat, Chormara, Kawasoti, Daldale, Rajahar, 16no, bhedabari, Gaindakot, Narayangarh',
                'distance' => '120',
                'company_id' => '2',
            ],
            [
                'name' => 'From Butwal to Chitwan',
                'origin' => 'Butwal',
                'destination' => 'Chitwan',
                'via' => 'Butwal, Bardaghat, Chormara, Kawasoti, Daldale, Rajahar, 16no, bhedabari, Gaindakot, Narayangarh',
                'distance' => '120',
                'company_id' => '5',
            ],
            [
                'name' => 'From Butwal to Chitwan',
                'origin' => 'Butwal',
                'destination' => 'Chitwan',
                'via' => 'Butwal, Bardaghat, Chormara, Kawasoti, Daldale, Rajahar, 16no, bhedabari, Gaindakot, Narayangarh',
                'distance' => '120',
                'company_id' => '6',
            ],
            [
                'name' => 'From Bhairahawa to Birjung',
                'origin' => 'Bhairahawa',
                'destination' => 'Birjung',
                'via' => 'Butwal, Bardaghat, Chormara, Kawasoti, Daldale, Rajahar, 16no, bhedabari, Gaindakot, Narayangarh, Manahari, Hetaunda, Birjung',
                'distance' => '145',
                'company_id' => '2',
            ],
            [
                'name' => 'From Birjung to Bhairahawa',
                'origin' => 'Birjung',
                'destination' => 'Butwal',
                'via' => 'Hetaunda, Manahari, Narayangarh, Gaindakot, Bhedabari, 16no, Rajahar, Daldale, Kawasoti, Chormara, Bardaghat, Butwal',
                'distance' => '145',
                'company_id' => '2',
            ],
            [
                'name' => 'From Kakarbitta to Mahendranagar',
                'origin' => 'Kakarbitta',
                'destination' => 'Mahendranagar',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '7',
            ],
            [
                'name' => 'From Mahendranagar to Kakarbitta',
                'origin' => 'Mahendranagar',
                'destination' => 'Kakarbitta',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '7',
            ],
            [
                'name' => 'From Jhapa to Mustang',
                'origin' => 'Jhapa',
                'destination' => 'Mustang',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '7',
            ],
            [
                'name' => 'From Mustang to Chitwan',
                'origin' => 'Mustang',
                'destination' => 'Chitwan',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '7',
            ],
            [
                'name' => 'From Chitwan to Jhapa',
                'origin' => 'Chitwan',
                'destination' => 'Jhapa',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '7',
            ],
            [
                'name' => 'From Chitwan to Dolakha',
                'origin' => 'Chitwan',
                'destination' => 'Dolakha',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '8',
            ],
            [
                'name' => 'From Dolakha to Kathamandu',
                'origin' => 'Dolakha',
                'destination' => 'Kathamandu',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '8',
            ],
            [
                'name' => 'From Nepalgunj to Illam',
                'origin' => 'Nepaljung',
                'destination' => 'Illam',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '8',
            ],
            [
                'name' => 'From Illam to Nepaljung',
                'origin' => 'Illam',
                'destination' => 'Nepaljung',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '8',
            ],
            [
                'name' => 'From Chitwan to Beshisahar',
                'origin' => 'Chitwan',
                'destination' => 'Beshisahar',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '9',
            ],
            [
                'name' => 'From Beshisahar to Chitwan',
                'origin' => 'Beshisahar',
                'destination' => 'Chitwan',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '9',
            ],
            [
                'name' => 'From Sundarbazar to Dumre',
                'origin' => 'Sundarbazar',
                'destination' => 'Dumre',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '9',
            ],
            [
                'name' => 'From Dumre to Sundarbazaar',
                'origin' => 'Dumre',
                'destination' => 'Sundarbazaar',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '9',
            ],
            [
                'name' => 'From Pokhara to Mustang',
                'origin' => 'Pokhara',
                'destination' => 'Mustang',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '9',
            ],
            [
                'name' => 'From Mustang to Pokhara',
                'origin' => 'Mustang',
                'destination' => 'Pokhara',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '9',
            ],
            [
                'name' => 'From Surkhet to Birjung',
                'origin' => 'Surkhet',
                'destination' => 'Birjung',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '9',
            ],
            [
                'name' => 'From Birjung to Surkhet',
                'origin' => 'Birjung',
                'destination' => 'Surkhet',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '9',
            ],
            [
                'name' => 'From Humla to Illam',
                'origin' => 'Humla',
                'destination' => 'Illam',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '10',
            ],
            [
                'name' => 'From Illam to Humla',
                'origin' => 'Illam',
                'destination' => 'Humla',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '10',
            ],
            [
                'name' => 'From Palpa to Hetaunda',
                'origin' => 'Palpa',
                'destination' => 'Hetaunda',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '10',
            ],
            [
                'name' => 'From Hetaunda to Butwal',
                'origin' => 'Hetaunda',
                'destination' => 'Butwal',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '10',
            ],
            [
                'name' => 'From Chitwan to Palpa',
                'origin' => 'Chitwan',
                'destination' => 'Palpa',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '10',
            ],
            [
                'name' => 'From Nepaljung to Janakpur',
                'origin' => 'Nepaljung',
                'destination' => 'Janakpur',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '10',
            ],
            [
                'name' => 'From Janakpur to Kathamandu',
                'origin' => 'Janakpur',
                'destination' => 'Kathamandu',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '10',
            ],
            [
                'name' => 'From Dang to Kathamandu',
                'origin' => 'Dang',
                'destination' => 'Kathamandu',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '2',
            ],
            [
                'name' => 'From Kathamandu to Dang',
                'origin' => 'Kathamandu',
                'destination' => 'Dang',
                'via' => 'Thankot, Naubise, Galchi, Malekhu, Muglin, Narayangarh',
                'distance' => '145',
                'company_id' => '2',
            ],
                

        ];

        DB::table('routes')->insert($routes);
    }
}
